name: CarChat
options:
  bundleIdPrefix: com.willsigmon
  xcodeVersion: "16.0"
  deploymentTarget:
    iOS: "18.6"
    watchOS: "10.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

schemes:
  CarChat-Compile:
    build:
      targets:
        CarChat: all
  CarChat-iOSOnly:
    build:
      targets:
        CarChat: all
    run:
      config: Debug
      executable: CarChat
    test:
      config: Debug
      targets:
        - CarChatTests
    profile:
      config: Release
      executable: CarChat
    analyze:
      config: Debug
    archive:
      config: Release
  CarChat-iOSBuildOnly:
    build:
      targets:
        CarChatiOSBuildOnly: all

packages:
  SwiftOpenAI:
    url: https://github.com/jamesrochabrun/SwiftOpenAI
    from: "4.0.0"
  SwiftAnthropic:
    url: https://github.com/jamesrochabrun/SwiftAnthropic
    from: "2.0.0"
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess
    from: "4.2.2"
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: "2.41.0"

settings:
  base:
    SWIFT_VERSION: "6.0"
    ALWAYS_SEARCH_USER_PATHS: NO

targets:
  CarChat:
    type: application
    platform: iOS
    supportedDestinations: [iOS]
    sources:
      - path: CarChat
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        IPHONEOS_DEPLOYMENT_TARGET: "18.6"
        INFOPLIST_FILE: CarChat/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: CarChat/Resources/CarChat.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 49HAGQE8FB
        PRODUCT_BUNDLE_IDENTIFIER: com.willsigmon.carchat
        PRODUCT_NAME: CarChat
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_STRICT_CONCURRENCY: complete
        SDKROOT: iphoneos
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        EXCLUDED_ARCHS[sdk=iphonesimulator*]: x86_64
      configs:
        Debug:
          ENABLE_TESTABILITY: YES
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
    dependencies:
      - package: SwiftOpenAI
      - package: SwiftAnthropic
      - package: KeychainAccess
      - package: Supabase
      - target: CarChatWatch
        embed: true
      - sdk: AuthenticationServices.framework
      - sdk: StoreKit.framework
      - sdk: UserNotifications.framework
      - sdk: CarPlay.framework
    preBuildScripts: []
    scheme:
      testTargets:
        - CarChatTests

  CarChatiOSBuildOnly:
    type: application
    platform: iOS
    supportedDestinations: [iOS]
    sources:
      - path: CarChat
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        IPHONEOS_DEPLOYMENT_TARGET: "18.6"
        INFOPLIST_FILE: CarChat/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: CarChat/Resources/CarChat.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 49HAGQE8FB
        PRODUCT_BUNDLE_IDENTIFIER: com.willsigmon.carchat.iosbuild
        PRODUCT_NAME: CarChat iOS Build
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_STRICT_CONCURRENCY: complete
        SDKROOT: iphoneos
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        EXCLUDED_ARCHS[sdk=iphonesimulator*]: x86_64
      configs:
        Debug:
          ENABLE_TESTABILITY: YES
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
    dependencies:
      - package: SwiftOpenAI
      - package: SwiftAnthropic
      - package: KeychainAccess
      - package: Supabase
      - sdk: AuthenticationServices.framework
      - sdk: StoreKit.framework
      - sdk: UserNotifications.framework
      - sdk: CarPlay.framework

  CarChatWatch:
    type: application.watchapp2
    platform: watchOS
    sources:
      - path: CarChatWatch/App
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        WATCHOS_DEPLOYMENT_TARGET: "10.0"
        SDKROOT: watchos
        SUPPORTED_PLATFORMS: "watchos watchsimulator"
        TARGETED_DEVICE_FAMILY: "4"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 49HAGQE8FB
        PRODUCT_BUNDLE_IDENTIFIER: com.willsigmon.carchat.watchkitapp
        PRODUCT_NAME: CarChat Watch
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: CarChatWatch/App/Info.plist
    dependencies:
      - target: CarChatWatchExtension

  CarChatWatchExtension:
    type: watchkit2-extension
    platform: watchOS
    sources:
      - path: CarChatWatch/Extension
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        WATCHOS_DEPLOYMENT_TARGET: "10.0"
        SDKROOT: watchos
        SUPPORTED_PLATFORMS: "watchos watchsimulator"
        TARGETED_DEVICE_FAMILY: "4"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 49HAGQE8FB
        PRODUCT_BUNDLE_IDENTIFIER: com.willsigmon.carchat.watchkitapp.watchkitextension
        PRODUCT_NAME: CarChat Watch Extension
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: CarChatWatch/Extension/Info.plist

  CarChatTests:
    type: bundle.unit-test
    platform: iOS
    supportedDestinations: [iOS]
    sources:
      - path: CarChatTests
    dependencies:
      - target: CarChat
    settings:
      base:
        SWIFT_VERSION: "6.0"
        IPHONEOS_DEPLOYMENT_TARGET: "18.6"
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_NAME: CarChatTests
        PRODUCT_BUNDLE_IDENTIFIER: com.willsigmon.carchat.tests
        SDKROOT: iphoneos
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        EXCLUDED_ARCHS[sdk=iphonesimulator*]: x86_64
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/CarChat.app/CarChat"
        BUNDLE_LOADER: "$(TEST_HOST)"
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@loader_path/Frameworks"
          - "@executable_path/Frameworks"
