name: CarChat
options:
  bundleIdPrefix: com.willsigmon
  xcodeVersion: "16.0"
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

packages:
  SwiftOpenAI:
    url: https://github.com/jamesrochabrun/SwiftOpenAI
    from: "4.0.0"
  SwiftAnthropic:
    url: https://github.com/jamesrochabrun/SwiftAnthropic
    from: "2.0.0"
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess
    from: "4.2.2"

settings:
  base:
    SWIFT_VERSION: "6.0"
    ALWAYS_SEARCH_USER_PATHS: NO

targets:
  CarChat:
    type: application
    platform: iOS
    supportedDestinations: [iOS]
    sources:
      - path: CarChat
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        INFOPLIST_FILE: CarChat/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: CarChat/Resources/CarChat.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 49HAGQE8FB
        PRODUCT_BUNDLE_IDENTIFIER: com.willsigmon.carchat
        PRODUCT_NAME: CarChat
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_STRICT_CONCURRENCY: complete
        SDKROOT: iphoneos
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        EXCLUDED_ARCHS[sdk=iphonesimulator*]: x86_64
      configs:
        Debug:
          ENABLE_TESTABILITY: YES
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
    dependencies:
      - package: SwiftOpenAI
      - package: SwiftAnthropic
      - package: KeychainAccess
    preBuildScripts: []
    scheme:
      testTargets:
        - CarChatTests

  CarChatWatch:
    type: application.watchapp2
    platform: watchOS
    sources:
      - path: CarChatWatch/App
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        WATCHOS_DEPLOYMENT_TARGET: "10.0"
        SDKROOT: watchos
        SUPPORTED_PLATFORMS: "watchos watchsimulator"
        TARGETED_DEVICE_FAMILY: "4"
        PRODUCT_BUNDLE_IDENTIFIER: com.willsigmon.carchat.watchkitapp
        PRODUCT_NAME: CarChat Watch
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: CarChat
        INFOPLIST_KEY_WKWatchKitApp: YES
        INFOPLIST_KEY_WKCompanionAppBundleIdentifier: com.willsigmon.carchat
    dependencies:
      - target: CarChatWatchExtension

  CarChatWatchExtension:
    type: watchkit2-extension
    platform: watchOS
    sources:
      - path: CarChatWatch/Extension
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        WATCHOS_DEPLOYMENT_TARGET: "10.0"
        SDKROOT: watchos
        SUPPORTED_PLATFORMS: "watchos watchsimulator"
        TARGETED_DEVICE_FAMILY: "4"
        PRODUCT_BUNDLE_IDENTIFIER: com.willsigmon.carchat.watchkitapp.watchkitextension
        PRODUCT_NAME: CarChat Watch Extension
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: CarChat
        INFOPLIST_KEY_NSExtension_NSExtensionPointIdentifier: com.apple.watchkit
        INFOPLIST_KEY_NSExtension_NSExtensionPrincipalClass: "$(PRODUCT_MODULE_NAME).ExtensionDelegate"
        INFOPLIST_KEY_WKAppBundleIdentifier: com.willsigmon.carchat.watchkitapp

  CarChatTests:
    type: bundle.unit-test
    platform: iOS
    supportedDestinations: [iOS]
    sources:
      - path: CarChatTests
    dependencies:
      - target: CarChat
    settings:
      base:
        SWIFT_VERSION: "6.0"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_NAME: CarChatTests
        PRODUCT_BUNDLE_IDENTIFIER: com.willsigmon.carchat.tests
        SDKROOT: iphoneos
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        EXCLUDED_ARCHS[sdk=iphonesimulator*]: x86_64
