name: CarChat
options:
  bundleIdPrefix: com.willsigmon
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "26.2"
  createIntermediateGroups: true
  generateEmptyDirectories: true

packages:
  SwiftOpenAI:
    url: https://github.com/jamesrochabrun/SwiftOpenAI
    from: "4.0.0"
  SwiftAnthropic:
    url: https://github.com/jamesrochabrun/SwiftAnthropic
    from: "2.0.0"
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess
    from: "4.2.2"

settings:
  base:
    SWIFT_VERSION: "6.0"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    ALWAYS_SEARCH_USER_PATHS: NO

targets:
  CarChat:
    type: application
    platform: iOS
    sources:
      - path: CarChat
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: CarChat/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: CarChat/Resources/CarChat.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.willsigmon.carchat
        PRODUCT_NAME: CarChat
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_STRICT_CONCURRENCY: complete
    dependencies:
      - package: SwiftOpenAI
      - package: SwiftAnthropic
      - package: KeychainAccess
    preBuildScripts: []

  CarChatTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: CarChatTests
    dependencies:
      - target: CarChat
    settings:
      base:
        SWIFT_VERSION: "6.0"
